# Configure.
env: WHAT=tests
go:
  - 1.7.3
language: go
matrix:
  include:
    - go: 1.7.3
      env: WHAT=Example from doc.go
      install:
        - mkdir $GOPATH/src/local; cd $_
        - sed '1,/Example Usage/d;/And the output is:/,$d' ~-/doc.go |tail -n +4 > main.go
        - go get ./...
      script: go run main.go
sudo: false

# Run.
install: make bootstrap
script: make
after_success:
  - bash <(curl -s https://codecov.io/bash)
